/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acap.com.buro.constantes;

/**
 *
 * @author acap1831
 */
public class datacredito {

    public static final StringBuffer ELIMINO_TARJETAS_TECNOCOM = new StringBuffer("delete @ta_lib.DATAC736DB  where  substr(F00001, 14,16)"
            + " in(select EMTANRTA from cartacdat.calgmit0) or substr(F00001, 14,16)  in (select EMTANRTA2 from cartacdat.calgmit0) "
            + " or  substr(F00001,105,11) in (select substr(cedula,01,03)||substr(cedula,05,07)|| substr(cedula,13,01) "
            + " from cartacdat.CEDULABLO ) ");

    public static final StringBuffer ELIMINA_PASAPORTES = new StringBuffer("delete from  @ta_lib.DATAC736DB   where   substr(F00001,105,11) "
            + "in     (select  digits(EMTANIDE)  from @ta_lib.CCSFEMTA   where EMTATIID='P') or  substr(F00001,14,16)  in  "
            + "(SELECT EMTANRTA FROM @ta_lib.CCSFEMTA   WHERE EMTACIFA='')    ");

    public static final StringBuffer ACTUALIZAR_COMA = new StringBuffer("UPDATE @TA_LIB.DATAC736DB SET F00001=REPLACE(F00001,',', '|') ");

    public static final StringBuffer AGREGAR_TARJETAS_VIEJAS = new StringBuffer("UPDATE @TA_LIB.DATAC736DB SET "
            + " F00001= substr(F00001,1,742)||(select cast(panant as char(16))  from @TA_LIB.tartjcte WHERE PAN=substr(F00001, 14,16) )"
            + " where  substr(F00001, 14,16) in (select PAN from @TA_LIB.tartjcte) ");

    public static final StringBuffer INSERTAR_TARJETAS_CASTIGADAS_VIGENTE = new StringBuffer("insert into @TA_LIB.DATAC736DB "
            + "SELECT  DISTINCT cast(trim(replace(D.CLNUID,'-','')) as char(12)) ||','||"
            + "EMTANRTA ||','||"
            + "cast(B.CLIAP1 as char(20))||','||"
            + "cast(B.CLIAP2 as char(20))||','||"
            + "cast(B.CLINO1 as char(20))||','||"
            + "case when B.CLISEX='F' then 'M' else 'V' end ||','||"
            + "cast(digits(B.CLANNA)||digits(B.CLMENA) ||digits(B.CLDINA) as char(8))||','||"
            + "cast(REPLACE(D.CLNUID,'-','') as char(12))||','||"
            + "cast(REPLACE(D.CLNUID,'-','') as char(12))||','||"
            + "cast( ifnull((select replace(cldire||cldir2||cldir3,',','') from v5clidat.cldicl12 xx where xx.CLDIRC=1 and  xx.cldoc=b.cldoc  FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast( ifnull((select replace(cldire||cldir2||cldir3,',','') from v5clidat.cldicl12 xx where xx.CLDIRC=2 and  xx.cldoc=b.cldoc  FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast( ifnull((select replace(cldire||cldir2||cldir3,',','') from v5clidat.cldicl12 xx where xx.CLDIRC=3 and  xx.cldoc=b.cldoc  FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast(IFNULL((select replace(CLDSDI,'-','') from v5clidat.cldedi03 where  CLCOSI=4 and cldoc =b.cldoc FETCH FIRST 1 ROWS ONLY),'') as char(10))||','||          "
            + "cast(IFNULL((select replace(CLDSDI,'-','') from v5clidat.cldedi03 where  CLCOSI=1 and cldoc =b.cldoc FETCH FIRST 1 ROWS ONLY),'') as char(10))||','||           "
            + "cast(IFNULL((select replace(CLDSDI,'-','') from v5clidat.cldedi03 where  CLCOSI=2 and cldoc =b.cldoc FETCH FIRST 1 ROWS ONLY),'') as char(10))||','||           "
            + "cast('9400000000' as char(10))||','||"
            + "cast(e.EMTAFUA1 as char(8))||','||          "
            + "LPAD(cast(EMTALCR1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTALCR2 as INTEGER),11,'0')||','||                "
            + " ifnull((select LPAD(cast((cacavi+cainme+cainac+casato+casaco) as INTEGER) ,11,'0') from cartacdat.cacredhist a,cartacdat.CALGMIT0 c  where a.canucr=c.canucr "
            + "  and  c.EMTANRTA=e.EMTANRTA and  date(a.ANOHIS||'-'||a.MESHIS||'-'||a.DIAHIS)=date('FECHAREMPLAZAR') and distip=24 FETCH FIRST 1 ROWS ONLY), '00000000000' ) ||','||             "
            + " ifnull((select LPAD(cast((cacavi+cainme+cainac+casato+casaco) as INTEGER) ,11,'0') from cartacdat.cacredhist a,cartacdat.CALGMIT0 c  where a.canucr=c.canucr "
            + "  and  c.EMTANRTA=e.EMTANRTA and  date(a.ANOHIS||'-'||a.MESHIS||'-'||a.DIAHIS)=date('FECHAREMPLAZAR') and distip=25 FETCH FIRST 1 ROWS ONLY), '00000000000' ) ||','||"
            + "LPAD(cast(EMTAPMI1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTAPMI2 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTASAC1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTASAC2 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0301 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0302 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0601 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0602 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0901 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0902 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1201 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1202 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1501 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1502 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1801 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1802 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2101 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2102 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2401 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2402 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2701 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2702 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3001 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3002 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3301 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3302 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3601 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3602 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTAFUP1 as INTEGER),8,'0')||','|| "
            + "LPAD(cast(EMTAFUP2 as INTEGER),8,'0')||','||"
            + "LPAD(cast(EMTAUPA1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTAUPA2 as INTEGER),11,'0')||','||"
            + "cast('' as char(9))||','|| "
            + "cast('' as char(16))"
            + "FROM  v5clidat.clpein b, v5clidat.clmcte d,"
            + "cartacdat.caccsfem e WHERE   b.cldoc=d.cldoc "
            + "and clnuid not in (select cedula from cartacdat.cedulablo) "
            + "and replace(clnuid,'-','')=digits(e.EMTANIDE) "
            + "and e.EMTANRTA in (select c.EMTANRTA FROM cartacdat.cacredhist a,cartacdat.CALGMIT0 c "
            + "WHERE   a.cacstc<>60  and a.caacan=0  and a.canucr=c.canucr "
            + "and date(a.ANOHIS||'-'||a.MESHIS||'-'||a.DIAHIS)=date('FECHAREMPLAZAR') "
            + " group by EMTANRTA)");

    public static final StringBuffer INSERTAR_TARJETAS_CASTIGADAS_CANCELADAS = new StringBuffer("insert into @TA_LIB.DATAC736DB "
            + "SELECT  cast(trim(replace(D.CLNUID,'-','')) as char(12)) ||','||"
            + "EMTANRTA ||','||"
            + "cast(B.CLIAP1 as char(20))||','||"
            + "cast(B.CLIAP2 as char(20))||','||"
            + "cast(B.CLINO1 as char(20))||','||"
            + "case when B.CLISEX='F' then 'M' else 'V' end ||','||"
            + "cast(digits(B.CLANNA)||digits(B.CLMENA) ||digits(B.CLDINA) as char(8))||','||"
            + "cast(REPLACE(D.CLNUID,'-','') as char(12))||','||"
            + "cast(REPLACE(D.CLNUID,'-','') as char(12))||','||"
            + "cast( ifnull((select replace(cldire||cldir2||cldir3,',','') from v5clidat.cldicl12 xx where xx.CLDIRC=1 and  xx.cldoc=b.cldoc  FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast( ifnull((select replace(cldire||cldir2||cldir3,',','') from v5clidat.cldicl12 xx where xx.CLDIRC=2 and  xx.cldoc=b.cldoc  FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast( ifnull((select replace(cldire||cldir2||cldir3,',','') from v5clidat.cldicl12 xx where xx.CLDIRC=3 and  xx.cldoc=b.cldoc  FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast(IFNULL((select replace(CLDSDI,'-','') from v5clidat.cldedi03 where  CLCOSI=4 and cldoc =b.cldoc FETCH FIRST 1 ROWS ONLY),'') as char(10))||','||          "
            + "cast(IFNULL((select replace(CLDSDI,'-','') from v5clidat.cldedi03 where  CLCOSI=1 and cldoc =b.cldoc FETCH FIRST 1 ROWS ONLY),'') as char(10))||','||           "
            + "cast(IFNULL((select replace(CLDSDI,'-','') from v5clidat.cldedi03 where  CLCOSI=2 and cldoc =b.cldoc FETCH FIRST 1 ROWS ONLY),'') as char(10))||','||           "
            + "cast('CANCELADA ' as char(10))||','||"
            + "cast(e.EMTAFUA1 as char(8))||','||          "
            + "LPAD(cast(EMTALCR1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTALCR2 as INTEGER),11,'0')||','||"
            + "'00000000000'  ||','||"
            + "'00000000000'  ||','||"
            + "LPAD(cast(EMTAPMI1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTAPMI2 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTASAC1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTASAC2 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0301 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0302 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0601 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0602 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0901 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA0902 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1201 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1202 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1501 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1502 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1801 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA1802 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2101 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2102 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2401 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2402 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2701 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA2702 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3001 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3002 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3301 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3302 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3601 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTA3602 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTAFUP1 as INTEGER),8,'0')||','|| "
            + "LPAD(cast(EMTAFUP2 as INTEGER),8,'0')||','||"
            + "LPAD(cast(EMTAUPA1 as INTEGER),11,'0')||','||"
            + "LPAD(cast(EMTAUPA2 as INTEGER),11,'0')||','||"
            + "cast('' as char(9))||','|| "
            + "cast('' as char(16))"
            + "FROM  v5clidat.clpein b,  "
            + "v5clidat.clmcte d,"
            + "cartacdat.caccsfem e WHERE   b.cldoc=d.cldoc "
            + "and clnuid not in (select cedula from cartacdat.cedulablo) "
            + "and replace(clnuid,'-','')=digits(e.EMTANIDE)"
            + "and e.EMTANRTA in (select c.EMTANRTA FROM cartacdat.cacredit a,cartacdat.CALGMIT0 c "
            + "WHERE   a.caacan<>0   and a.cacstc=60  and a.canucr=c.canucr "
            + "and date(a.caacan||'-'||a.camcan||'-'||a.cadcan)<=date('FECHAREMPLAZAR')"
            + "and date(a.caacan||'-'||a.camcan||'-'||a.cadcan)>=(date('FECHAREMPLAZAR') - 3 MONTHS)"
            + "and  e.EMTANRTA not in (select c.EMTANRTA FROM cartacdat.cacredhist a,cartacdat.CALGMIT0 c \n" 
            + "WHERE   a.cacstc<>60  and a.caacan=0  and a.canucr=c.canucr \n"
            + "and date(a.ANOHIS||'-'||a.MESHIS||'-'||a.DIAHIS)=date('2023-09-15')) "
            + " group by EMTANRTA)");

    public static StringBuffer DIRECCION = new StringBuffer(" UPDATE @ta_lib.DATAC736DB  set"
            + " f00001= substr(f00001,1,129)||','|| cast( ifnull((select replace(cldire||cldir2||cldir3,',','') "
            + "from v5clidat.cldicl12 xx,v5clidat.clmcte yy where xx.CLDIRC=1 and  xx.cldoc=yy.cldoc "
            + "and replace(yy.clnuid,'-','')=substr(f00001,105,12) FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast( ifnull((select replace(cldire||cldir2||cldir3,',','') from "
            + "v5clidat.cldicl12 xx ,v5clidat.clmcte yy where xx.CLDIRC=2 and  xx.cldoc=yy.cldoc "
            + "and replace(yy.clnuid,'-','')=substr(f00001,105,12)FETCH FIRST 1 ROWS ONLY),'') as char(40))||','||"
            + "cast(ifnull((select replace(cldire||cldir2||cldir3,',','') from "
            + "v5clidat.cldicl12 xx ,v5clidat.clmcte yy where xx.CLDIRC=3 and   "
            + "xx.cldoc=yy.cldoc and replace(yy.clnuid,'-','')=substr(f00001,105,12)  FETCH FIRST 1 ROWS ONLY),'') as char(40))"
            + "||substr(f00001,253,507)  where substr(f00001,132,2)='' ");
}
